In [ ]:
#Write a NumPy program to broadcast on different shapes of arrays 
#where p(3,3) + q(3).

In [1]:
import numpy as np    
p = np.array([[1, 1, 1],
              [2, 3, 4],
              [5, 6, 7]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:
Array-1
[[1 1 1]
 [2 3 4]
 [5 6 7]]
Array-2
[10 11 12]

New Array:
[[11 12 13]
 [12 14 16]
 [15 17 19]]


In [ ]:
#How to get the second largest value of an array when grouped by another array?

In [8]:
arr = np.array([43,12,1,2,4,5,6])
print("Original array: ",arr)
arr1 = np.sort(arr)
no = 3
k = 7
print("The second largest element of an array : ")
print(arr1[len(arr)-no:k-1])

Original array:  [43 12  1  2  4  5  6]
The second largest element of an array : 
[ 6 12]


In [ ]:
#How to find the position of missing values in numpy array?

In [11]:
nums = np.array([[13, 22, np.nan, 1],
              [10, 2, 10, 9],
              [51, np.nan, 11, np.nan]])

print("Original array:") 
print(nums)
print("\nFind the missing data of the array:")
print(np.isnan(nums))

Original array:
[[13. 22. nan  1.]
 [10.  2. 10.  9.]
 [51. nan 11. nan]]

Find the missing data of the array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
#Write a NumPy program to create a 3x3x3 array with random values. 

In [36]:
x = np.random.random((3,3,3))
print(x)

[[[0.55772847 0.63878648 0.86627997]
  [0.8928272  0.75996712 0.33104028]
  [0.06749615 0.07581441 0.91051186]]

 [[0.40825717 0.92907896 0.48976955]
  [0.72660343 0.45024875 0.43037392]
  [0.27344993 0.99827641 0.5253978 ]]

 [[0.97476239 0.21747164 0.91024512]
  [0.73954354 0.71598964 0.40809467]
  [0.84848385 0.01415884 0.40613426]]]


In [ ]:
#Write a NumPy program to get the unique elements of an array.

In [39]:
a = np.array([[1, 2], [2, 3]])
print("Original array:")
print(a)
print("Unique elements of the above array:")
print(np.unique(a))

Original array:
[[1 2]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [ ]:
#Write a NumPy program to get the values and indices of the elements 
#that are bigger than 10 in a given array

In [42]:
b = np.array([[0, 10, 50], [40, 80, 60]])
print("Original array: ")
print(b)
print("\nValues bigger than 10 =", b[b>10])
print("\nTheir indices are : ", np.nonzero(b > 10))

Original array: 
[[ 0 10 50]
 [40 80 60]]

Values bigger than 10 = [50 40 80 60]

Their indices are :  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [ ]:
#Write a NumPy program to get the powers of an array values element-wise.

In [45]:
x = np.arange(11)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 2))

Original array
[ 0  1  2  3  4  5  6  7  8  9 10]
First array elements raised to powers from second array, element-wise:
[  0   1   4   9  16  25  36  49  64  81 100]


In [ ]:
# Write a NumPy program to remove the negative values in a NumPy array with 0.

In [62]:
arr1 = np.array([1, 2, -3, 3, 4, -5, -6, 5, -7, -8, 6, 7, -9, 8])
print("Original array : ",arr1)
  
# code to replace all negative value with 0
result = np.where(arr1<0, 0,arr1)
print("New resulting array: ", result)

Original array :  [ 1  2 -3  3  4 -5 -6  5 -7 -8  6  7 -9  8]
New resulting array:  [1 2 0 3 4 0 0 5 0 0 6 7 0 8]


In [ ]:
# Write a NumPy program to calculate the absolute value element-wise

In [49]:
arr = np.array([1, -2, 3, -4, 5, -6])
print("Given array :",arr)
result = np.absolute(arr)
print("\nAbsolute array :",result)

Given array : [ 1 -2  3 -4  5 -6]

Absolute array : [1 2 3 4 5 6]


In [ ]:
 Write a NumPy program to replace odd number in 2d array by its square . 

In [59]:
          #  O  E  O  E    O  E  O  E  
x=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original array : \n",x)
ans = (x[x%2 != 0])**2
print ("By replacing odd number in 2d array by its square : \n",ans)

Original array : 
 [[1 2 3 4]
 [5 6 7 8]]
By replacing odd number in 2d array by its square : 
 [ 1  9 25 49]


In [ ]:
#Write a NumPy program to create random vector of size 15 and 
#replace the maximum value by -1.

In [61]:
a = np.random.random(15)
print("Original array :")
print(a)
a[a.argmax()] = -1
print("\nMaximum value replaced by -1:")
print(a)

Original array :
[0.51385714 0.29646011 0.04056518 0.39019845 0.01225215 0.60915952
 0.75654511 0.99410451 0.63922964 0.61835142 0.14503247 0.40734239
 0.0243969  0.5316788  0.6285475 ]

Maximum value replaced by -1:
[ 0.51385714  0.29646011  0.04056518  0.39019845  0.01225215  0.60915952
  0.75654511 -1.          0.63922964  0.61835142  0.14503247  0.40734239
  0.0243969   0.5316788   0.6285475 ]
