In [ ]:
#Write a NumPy program to test element-wise for NaN of a given array.

In [2]:
import numpy as np
a = np.array([1, 0, np.nan, np.inf])
print("Original array : ",a)
print("Test element-wise for NaN : ",np.isnan(a))

Original array :  [ 1.  0. nan inf]
Test element-wise for NaN :  [False False  True False]


In [ ]:
#Write a NumPy program to create an array with values ranging from 12 to 38.

In [6]:
x = np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [ ]:
#Write a NumPy program to reverse an array (first element becomes last).

In [10]:
x = np.arange(10,21)
print("Original array :",x)
x = x[::-1]
print("Reverse array : ",x)

Original array : [10 11 12 13 14 15 16 17 18 19 20]
Reverse array :  [20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#Write a NumPy program to convert an array to a float type

In [11]:
a1 = np.ones(4, dtype="float")
print(a1)

[1. 1. 1. 1.]


In [ ]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [15]:
x = np.ones((5,5),dtype = 'int')
print("Original array : ")
print(x)
print("1 on the border and 0 inside in the array : ")
x[1:-1,1:-1] = 0
print(x)

Original array : 
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 on the border and 0 inside in the array : 
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Write a NumPy program to append values to the end of an array.

In [16]:
x = [10, 20, 30]
print("Original array : ")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array : ")
print(x)

Original array : 
[10, 20, 30]
After append values to the end of the array : 
[10 20 30 40 50 60 70 80 90]


In [ ]:
#Write a NumPy program to test whether each element of a 1-D array is also present in a second array

In [18]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2 : ")
print(np.in1d(array1,array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2 : 
[ True False False  True False]


In [ ]:
#Write a NumPy program to get the unique elements of an array

In [22]:
#finding unique element for 1D array:

x = np.array([10, 10, 20, 20, 30, 30])
print("Original array:",x)
print("Unique elements of 1D array are :",np.unique(x))


#finding unique element for 2D array:

x = np.array([[1, 1], [2, 3]])
print("Original array:")
print(x)
print("Unique elements of 2D array are :",np.unique(x))

Original array: [10 10 20 20 30 30]
Unique elements of 1D array are : [10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of 2D array are : [1 2 3]


In [ ]:
#Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array

In [24]:
#             0  1  2  3  4  5
x = np.array([1, 2, 3, 4, 5, 6])
print("Original array: ",x)
print("Maximum Values: ",np.argmax(x))
print("Minimum Values: ",np.argmin(x))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


In [ ]:
#Write a NumPy program to create a contiguous flattened array

In [26]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print("Original array:")
print(x)
y = np.ravel(x)
print("New flattened array:",y)
#print(y)

Original array:
[[10 20 30]
 [20 40 50]]
New flattened array: [10 20 30 20 40 50]


In [ ]:
#Write a NumPy program to concatenate two 2-dimensional arrays

In [32]:
# Creating two 2D arrays
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
print("Array 1 : ")
print(arr1)
print("Array 2 : ")
print(arr2)
 
# Concatenating operation
# axis = 1 implies that it is being done column-wise
conarr = np.concatenate((arr1,arr2),axis=1)
print("Concatenated array : ")
print(conarr)

Array 1 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2 : 
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Concatenated array : 
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [ ]:
#Write a NumPy program to convert 1-D arrays as columns into a 2-D array

In [36]:
# 1-D array having elements [1 2 3 4 5 6 7 8]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
  
# Print the 1-D array
print ('Before reshaping:',arr)

arr2 = arr.reshape(2, 4)
print ('After reshaping having dimension 2x4:')
print (arr2)

Before reshaping: [1 2 3 4 5 6 7 8]
After reshaping having dimension 2x4:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Write a NumPy program (using NumPy) to sum of all the multiples of 3 or 5 below 100. 

In [38]:
x = np.arange(1, 100)
# find  multiple of 3 or 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:100])
# print sum the numbers
print("Sum : ",n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum :  2318


In [ ]:
#Write a NumPy program to get the index of a maximum element in a NumPy array along one 
#axis.

In [3]:
a = np.array([[1,2,3],[4,3,1]])
print("Original array:")
print(a)
i,j = np.unravel_index(a.argmax(), a.shape)
print("Index of a maximum element in a numpy array along one axis:")
print(a[i,j])

Original array:
[[1 2 3]
 [4 3 1]]
Index of a maximum element in a numpy array along one axis:
4


In [ ]:
#Write a NumPy program to stack 1-D arrays as row wise. 

In [7]:
print("\nOriginal arrays:")
x = np.array((1,2,3))
y = np.array((2,3,4))
print("Array-1 : ",x)
print("Array-2 : ",y)
new_array =  np.row_stack((x, y))
print("Stack 1-D arrays as rows wise:")
print(new_array)


Original arrays:
Array-1 :  [1 2 3]
Array-2 :  [2 3 4]
Stack 1-D arrays as rows wise:
[[1 2 3]
 [2 3 4]]


In [ ]:
#Write a NumPy program to stack 1-D arrays as column wise. 

In [8]:
print("\nOriginal arrays:")
x = np.array((1,2,3))
y = np.array((2,3,4))
print("Array-1 : ",x)
print("Array-2 : ",y)
new_array =  np.column_stack((x, y))
print("Stack 1-D arrays as rows wise:")
print(new_array)


Original arrays:
Array-1 :  [1 2 3]
Array-2 :  [2 3 4]
Stack 1-D arrays as rows wise:
[[1 2]
 [2 3]
 [3 4]]


In [ ]:
#Write a NumPy program to get the minimum and maximum value of a given array along the second axis. 

In [11]:
arr = np.array([[0, 1],[2, 3]])
  
print("Given Array : ")
print(arr)
# find row-wise max values 
r1 = np.amax(arr, 1)
print("Maximum Value:",r1)
  
# find row-wise min values
r2 = np.amin(arr, 1)
print("Minimum Value:",r2)

Given Array : 
[[0 1]
 [2 3]]
Maximum Value: [1 3]
Minimum Value: [0 2]
